// data.ts

export const metadata = {
    title: "cliniQX invent",
    description: "Generated by create next app",
    icons: {
      icon: ["/favicon.ico"],
      apple: ["/apple-touch-icon.png"],
      shortcut: ["/apple-touch-icon.png"],
    },
    manifest: "/site.webmanifest",
  };
  