export const metadata = {
  title: "cliniQX invent",
  description: "Generated by create next app",
  icons: {
    icon: ["/favicon.ico"],
    apple: ["/apple-touch-icon.png"],
    shortcut: ["/apple-touch-icon.png"],
  },
  manifest: "/site.webmanifest",
  fonts: [
    "https://fonts.googleapis.com/css2?family=Capriola&family=Baumans&family=Poppins:wght@300;400;500;600&display=swap",
  ],
};
