// List of all body parts IDs used in the SVG and across the application
export const bodyParts = [
    "brain",
    "heart",
    "lungs",
    "kidneys",
    "eyes",
    "thymus",
    "thyroid",
    "spleen",
    "pancreas",
    "stomach",
    "liver",
    "gallbladder",
    "smallIntestine",
    "largeIntestine",
    "appendix",
    "skeleton",
    "tibia",
    "fibula",
    "femur",
    "patella",
    "foot",
    "pelvis",
    "sacrum",
    "coccyx",
    "scapulae",
    "spine",
    "ribs",
    "sternum",
    "skull",
    "mandible",
    "clavicle",
    "radius",
    "ulna",
    "humerus",
    "handCarpals",
    "metacarpals",
    "phalanges",
    "circulatorySystem"
  ];
  
  export default bodyParts;
  